defaults:
  - _self_
  - data: finetune
  - logger: default
  - logging: default
  - optimizer: adamw
  - model: finetune
  - trainer: finetune
  - decode: default
hydra:  
  output_subdir: null  
  run:  
    dir: .
project_name: raven_test
experiment_name:
num_workers: 8
fix_seed: True
slurm_job_id:
train: False
wandb: True
verbose: False
log_wandb: True
test_on_one_gpu: True
gpus: 1
exp_dir:
exp_name:
logging_dir: /ssd_scratch/cvit/akshat/
log_folder:
speaker: eleanor
finetune: full