wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/finetune_deaf.py
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732469341.595724
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.2
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
